#pragma checksum "C:\Users\G531\Desktop\ProyectoUWPEnBlanco\ProyectoUWPEnBlanco\App.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CDF0C138DC9EAF31402EBE04EC37F3EC5CC72E28B411BBD00177522A3DE4076C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUWPEnBlanco
{
    partial class App : global::Windows.UI.Xaml.Application
    {
    }
}

