#pragma checksum "C:\Users\G531\Desktop\ProyectoUWPEnBlanco\ProyectoUWPEnBlanco\OddishJCS.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CDC60AAD13DA716ACF0428F4496246D586AD8542BDE102A328CDA7F11D567F86"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoUWPEnBlanco
{
    partial class OddishJCS : 
        global::Windows.UI.Xaml.Controls.UserControl, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 0.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 2: // OddishJCS.xaml line 348
                {
                    this.imFondo = (global::Windows.UI.Xaml.Controls.Image)(target);
                }
                break;
            case 3: // OddishJCS.xaml line 510
                {
                    this.imgPotionRed = (global::Windows.UI.Xaml.Controls.Image)(target);
                    ((global::Windows.UI.Xaml.Controls.Image)this.imgPotionRed).PointerPressed += this.UsePotionRed;
                }
                break;
            case 4: // OddishJCS.xaml line 517
                {
                    this.imgPotionYellow = (global::Windows.UI.Xaml.Controls.Image)(target);
                    ((global::Windows.UI.Xaml.Controls.Image)this.imgPotionYellow).PointerPressed += this.UsePotionYellow;
                }
                break;
            case 5: // OddishJCS.xaml line 524
                {
                    this.pbHealth = (global::Windows.UI.Xaml.Controls.ProgressBar)(target);
                    ((global::Windows.UI.Xaml.Controls.ProgressBar)this.pbHealth).ValueChanged += this.pbHealth_ValueChanged;
                }
                break;
            case 6: // OddishJCS.xaml line 531
                {
                    this.pbEnergy = (global::Windows.UI.Xaml.Controls.ProgressBar)(target);
                    ((global::Windows.UI.Xaml.Controls.ProgressBar)this.pbEnergy).ValueChanged += this.pbEnergy_ValueChanged;
                }
                break;
            case 7: // OddishJCS.xaml line 538
                {
                    this.pokemonNombre = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 8: // OddishJCS.xaml line 356
                {
                    this.SinPatasNiHojas = (global::Windows.UI.Xaml.Controls.Canvas)(target);
                }
                break;
            case 9: // OddishJCS.xaml line 475
                {
                    this.EscudoCanvas = (global::Windows.UI.Xaml.Controls.Canvas)(target);
                }
                break;
            case 10: // OddishJCS.xaml line 479
                {
                    this.Escudo = (global::Windows.UI.Xaml.Shapes.Ellipse)(target);
                }
                break;
            case 11: // OddishJCS.xaml line 364
                {
                    this.CuerpoRedondo = (global::Windows.UI.Xaml.Shapes.Path)(target);
                }
                break;
            case 12: // OddishJCS.xaml line 382
                {
                    this.Boca = (global::Windows.UI.Xaml.Shapes.Path)(target);
                }
                break;
            case 13: // OddishJCS.xaml line 401
                {
                    this.PataDerecha = (global::Windows.UI.Xaml.Shapes.Path)(target);
                }
                break;
            case 14: // OddishJCS.xaml line 413
                {
                    this.OjoIzquiero = (global::Windows.UI.Xaml.Shapes.Ellipse)(target);
                }
                break;
            case 15: // OddishJCS.xaml line 424
                {
                    this.OjoDerecho = (global::Windows.UI.Xaml.Shapes.Ellipse)(target);
                }
                break;
            case 16: // OddishJCS.xaml line 435
                {
                    this.PataIzquierda = (global::Windows.UI.Xaml.Shapes.Path)(target);
                }
                break;
            case 17: // OddishJCS.xaml line 447
                {
                    this.HojasAgrupado = (global::Windows.UI.Xaml.Controls.Canvas)(target);
                }
                break;
            case 18: // OddishJCS.xaml line 451
                {
                    this.Hojas1 = (global::Windows.UI.Xaml.Shapes.Path)(target);
                }
                break;
            case 19: // OddishJCS.xaml line 462
                {
                    this.Hojas2 = (global::Windows.UI.Xaml.Shapes.Path)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        /// <summary>
        /// GetBindingConnector(int connectionId, object target)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 0.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

